source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MMChatBarDemo_Example', :exclusive => true do
  pod 'MMChatBarDemo', :path => '../'
end

target 'MMChatBarDemo_Tests', :exclusive => true do
  pod 'MMChatBarDemo', :path => '../'

  pod 'FBSnapshotTestCase'
end
